server:
  port: 8091
  
  
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/certificate-management?allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:mysql://9.30.194.198:3306/crtmngmntdb?allowPublicKeyRetrieval=true&useSSL=false
    #username: root
    username: crtmngmntuser
    #password: abc@123
    password: crtmngmntuS3r@ll
  jpa:
    hibernate:
      ddl-auto: update    
       