server:
  port: 8091
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/certificate-management?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: abc@123
    
  jpa:
    hibernate:
      ddl-auto: update    
       